In [25]:
import pandas as pd
df = pd.read_csv('../data/tima_cleaned_data_v1.csv')
df

,STT,application_date,TS_CREDIT_SCORE_V2,Số điện thoại khách hàng,FromDate,ID,LoanID,Số tiền đăng ký vay ban đầu,Tiền giải ngân,Tiền gốc còn lại,...,AgeGroup,LoanTermMonths,ProcessingDays,LoanToIncomeRatio,Cần Giải Ngân,Đã trả/khoản vay đã giải ngân,LowCreditScore,CreditScoreGroup,IncomeBracket,LoanStatus
0,2,NaN,403,977966899,2016-06-24,40,16104,10000000.0,10000000.0,10000000.0,...,Unknown,1,NaN,1.30,0.0,1.00,1,Low (High Risk),5-10m,Active
1,3,2016-07-28,403,977966899,2016-07-28,226,20871,10000000.0,10000000.0,0.0,...,26-35,8,0.0,1.30,0.0,0.00,1,Low (High Risk),5-10m,Completed
2,4,2016-06-29,531,397511119,2016-06-29,45,17049,5000000.0,5000000.0,5000000.0,...,Unknown,6,0.0,0.19,0.0,1.00,1,Low (High Risk),>=25m,Completed
3,5,2016-06-29,588,abc1234567,2016-06-29,48,17067,10000000.0,10000000.0,10000000.0,...,26-35,4,0.0,1.25,0.0,1.00,1,Low (High Risk),5-10m,Completed
4,6,2016-08-05,675,966710180,2016-08-05,293,22390,10000000.0,10000000.0,0.0,...,26-35,4,0.0,0.83,0.0,0.00,0,Medium,10-15m,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,3181,2018-12-24,577,353833091,2018-12-24,327685,56967,5000000.0,5000000.0,1814424.0,...,18-25,3,0.0,0.67,0.0,0.36,1,Low (High Risk),5-10m,Active
2379,3182,2018-12-22,638,967295514,2018-12-22,329444,56835,3000000.0,3000000.0,3000000.0,...,Unknown,2,0.0,0.38,0.0,1.00,0,Medium,5-10m,Completed
2380,3184,2018-12-27,605,385669091,2018-12-27,333862,57212,6000000.0,6000000.0,6000000.0,...,26-35,3,0.0,0.75,0.0,1.00,0,Medium,5-10m,Completed
2381,3187,2019-01-10,597,869625266,2019-01-10,348341,57938,7000000.0,6000000.0,6000000.0,...,26-35,3,0.0,0.58,1000000.0,1.00,1,Low (High Risk),10-15m,Completed
2382,3188,2019-01-13,548,383429652,2019-01-13,351190,58148,10000000.0,10000000.0,10000000.0,...,18-25,3,0.0,0.71,0.0,1.00,1,Low (High Risk),10-15m,Active

In [26]:
#Create Dim_Customer
import pandas as pd

cust_cols = [
    "CardNumber","FullName","Gender","Birthday","Age","AgeGroup",
    "JobName","Salary","Hình thức cư trú", "TS_CREDIT_SCORE_V2","LowCreditScore", "CreditScoreGroup",
    "IncomeBracket","HasBadDebt"
]

dim_customer = df[cust_cols].drop_duplicates(subset=["CardNumber"]).reset_index(drop=True)
dim_customer.to_csv("../data/Dim_Fact Table/Dim_Customer.csv", index=False, encoding="utf-8-sig")
dim_customer.shape
dim_customer

,CardNumber,FullName,Gender,Birthday,Age,AgeGroup,JobName,Salary,Hình thức cư trú,TS_CREDIT_SCORE_V2,LowCreditScore,CreditScoreGroup,IncomeBracket,HasBadDebt
0,12603108,Phạm Sơn Tùng,0.0,1987-12-16,NaN,Unknown,Khác,7700000.0,Thuộc sở hữu của họ hàng,403,1,Low (High Risk),5-10m,0
1,1075003746,Đào Công Quyết,0.0,NaN,NaN,Unknown,Nhân viên chính thức,26000000.0,Đồng sở hữu,531,1,Low (High Risk),>=25m,0
2,1089003832,12345,0.0,1989-10-04,27.0,26-35,Nhân viên chính thức,8000000.0,Sở hữu cá nhân,588,1,Low (High Risk),5-10m,0
3,1182005991,Đào Ngọc Linh,1.0,1982-01-31,34.0,26-35,Khác,12000000.0,Đồng sở hữu,675,0,Medium,10-15m,0
4,1188000582,Đỗ Minh Trang,1.0,1988-01-01,28.0,26-35,Nhân viên chính thức,8000000.0,Thuộc sở hữu của họ hàng,582,1,Low (High Risk),5-10m,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,331764079,Nguyễn Hoài Duy,0.0,1996-12-09,22.0,18-25,Công nhân,7500000.0,Thuê,577,1,Low (High Risk),5-10m,0
1864,60526843,Trần Hùng Mạnh,Unknown,NaN,NaN,Unknown,Khác,8000000.0,Khác,638,0,Medium,5-10m,0
1865,35091001441,Lưu Văn Hạng,0.0,1991-11-09,27.0,26-35,Kinh doanh,8000000.0,Nhà sở hữu,605,0,Medium,5-10m,0
1866,151505959,Nguyễn Văn Trọng,0.0,1985-12-02,34.0,26-35,Tự doanh không ĐKKD,12000000.0,Thuê,597,1,Low (High Risk),10-15m,0
1867,30094001694,Phạm Đức Hùng,0.0,1994-10-25,25.0,18-25,Shipper(Giao hàng),14000000.0,Thuê,548,1,Low (High Risk),10-15m,0

In [27]:
#Create Dim_Product
prod_cols = ["ProductCreditName","InterestPaymentType"]
dim_product = df[prod_cols].drop_duplicates(subset=["ProductCreditName"]).reset_index(drop=True)
dim_product.to_csv("../data/Dim_Fact Table/Dim_Product.csv", index=False, encoding="utf-8-sig")
dim_product.shape
dim_product

         ProductCreditName         InterestPaymentType
0        Cầm cố Điện thoại                    Lãi ngày
1                  Unknown                    Lãi ngày
2            Cầm cố xe máy                    Lãi ngày
3        Cầm cố xe máy KCC            Tất toán cuối kỳ
4             Vay theo sim                    Lãi ngày
5     Cầm cố Điện thoại HK  Dư nợ giảm dần theo chu kỳ
6           Cầm Sim Số Đẹp            Tất toán cuối kỳ
7          Đăng ký xe ô tô            Tất toán cuối kỳ
8           Ô tô ngân hàng                    Lãi ngày
9   Vay trực tuyến qua Sim            Tất toán cuối kỳ
10                Cầm ô tô            Tất toán cuối kỳ

In [28]:
#Create Dim_Date from application_date
# Do not touch df; only temporarily change the format to create the date range.
dates = pd.to_datetime(df["application_date"], errors="coerce")
dim_date = pd.DataFrame({"Date": pd.date_range(dates.min(), dates.max(), freq="D")})
dim_date["Year"]      = dim_date["Date"].dt.year
dim_date["Quarter"]   = "Q" + dim_date["Date"].dt.quarter.astype(str)
dim_date["MonthNum"]  = dim_date["Date"].dt.month
dim_date["MonthName"] = dim_date["Date"].dt.strftime("%b")
dim_date["MonthYear"] = dim_date["Date"].dt.strftime("%b %Y")
dim_date["Day"]       = dim_date["Date"].dt.day
dim_date["DayOfWeek"] = dim_date["Date"].dt.weekday + 1  # 1=Mon..7=Sun

dim_date.to_csv("../data/Dim_Fact Table/Dim_Date.csv", index=False, encoding="utf-8-sig")
dim_date.shape
dim_date

          Date  Year Quarter  MonthNum MonthName MonthYear  Day  DayOfWeek
0   2016-06-29  2016      Q2         6       Jun  Jun 2016   29          3
1   2016-06-30  2016      Q2         6       Jun  Jun 2016   30          4
2   2016-07-01  2016      Q3         7       Jul  Jul 2016    1          5
3   2016-07-02  2016      Q3         7       Jul  Jul 2016    2          6
4   2016-07-03  2016      Q3         7       Jul  Jul 2016    3          7
..         ...   ...     ...       ...       ...       ...  ...        ...
929 2019-01-14  2019      Q1         1       Jan  Jan 2019   14          1
930 2019-01-15  2019      Q1         1       Jan  Jan 2019   15          2
931 2019-01-16  2019      Q1         1       Jan  Jan 2019   16          3
932 2019-01-17  2019      Q1         1       Jan  Jan 2019   17          4
933 2019-01-18  2019      Q1         1       Jan  Jan 2019   18          5

[934 rows x 8 columns]

In [29]:
#Create Dim_Geography
geo_cols = ["CityName","DistrictName"]
if geo_cols:
    dim_geography = df[geo_cols].drop_duplicates().reset_index(drop=True)
    dim_geography.to_csv("../data/Dim_Fact Table/Dim_Geography.csv", index=False, encoding="utf-8-sig")
    dim_geography.shape
dim_geography

       CityName  DistrictName
0        Hà Nội     Hoàng Mai
1        Hà Nội       Đống Đa
2        Hà Nội       Ba Đình
3        Hà Nội     Thanh Trì
4        Hà Nội       Hà Đông
5        Hà Nội      Cầu Giấy
6        Hà Nội   Bắc Từ Liêm
7        Hà Nội     Long Biên
8        Hà Nội   Nam Từ Liêm
9        Hà Nội    Thanh Xuân
10       Hà Nội        Tây Hồ
11       Hà Nội  Hai Bà Trưng
12       Hà Nội     Hoàn Kiếm
13       Hà Nội    Đan Phượng
14       Hà Nội      Hoài Đức
15       Hà Nội       Mê Linh
16       Hà Nội      Đông Anh
17       Hà Nội       Sóc Sơn
18       Hà Nội       Gia Lâm
19     Hòa Bình      Hòa Bình
20  Hồ Chí Minh            12
21    Hải Dương     Hải Dương
22      Phú Thọ      Việt Trì
23    Vĩnh Phúc      Vĩnh Yên
24     Bắc Ninh      Bắc Ninh
25      Lào Cai       Lào Cai
26    Thanh Hóa     Thanh Hóa
27    Hải Phòng     Ngô Quyền
28  Hồ Chí Minh             3
29  Hồ Chí Minh             6
30  Hồ Chí Minh             1
31  Hồ Chí Minh             5
32  Hồ Chí Minh            10
33  Hồ Chí Minh     Phú Nhuận
34  Hồ Chí Minh    Bình Thạnh
35  Hồ Chí Minh             2
36  Hồ Chí Minh      Tân Bình
37  Hồ Chí Minh             8
38  Hồ Chí Minh       Thủ Đức
39  Hồ Chí Minh      Bình Tân
40  Hồ Chí Minh       Tân Phú
41  Hồ Chí Minh        Củ Chi
42  Hồ Chí Minh        Nhà Bè
43       Hà Nội    Thường Tín
44  Hồ Chí Minh    Bình Chánh
45  Hồ Chí Minh        Gò Vấp
46  Hồ Chí Minh             7
47       Hà Nội      Quốc Oai
48  Hồ Chí Minh             9
49       Hà Nội         Ba Vì
50  Hồ Chí Minh       Hóc Môn
51       Hà Nội       Sơn Tây
52       Hà Nội     Chương Mỹ
53  Hồ Chí Minh             4
54  Hồ Chí Minh            11
55  Thái Nguyên        Đại Từ
56     Đồng Nai        Cẩm Mỹ
57      Yên Bái       Yên Bái

In [30]:
#Create Dim_Geography2
geo_cols = ["CityName"]
if geo_cols:
    dim_geography = df[geo_cols].drop_duplicates().reset_index(drop=True)
    dim_geography.to_csv("../data/Dim_Fact Table/Dim_Geography2.csv", index=False, encoding="utf-8-sig")
    dim_geography.shape
dim_geography

       CityName
0        Hà Nội
1      Hòa Bình
2   Hồ Chí Minh
3     Hải Dương
4       Phú Thọ
5     Vĩnh Phúc
6      Bắc Ninh
7       Lào Cai
8     Thanh Hóa
9     Hải Phòng
10  Thái Nguyên
11     Đồng Nai
12      Yên Bái

In [31]:
#Create Fact_Loan table (containing information about loans)
fact_cols = [
    "LoanID","CardNumber","ProductCreditName","application_date","CityName", "Số tiền đăng ký vay ban đầu",
    "Tiền giải ngân","Cần Giải Ngân", "Tiền gốc còn lại", "Đã trả/khoản vay đã giải ngân","LongestOverdue","LoanTermMonths",
    "LoanToIncomeRatio","HasLatePayment","HasBadDebt","LoanStatus"
]

fact_loans = df[fact_cols].copy()

fact_loans.to_csv("../data/Dim_Fact Table/Fact_Loans.csv", index=False, encoding="utf-8-sig")
fact_loans.shape
fact_loans

,LoanID,CardNumber,ProductCreditName,application_date,CityName,Số tiền đăng ký vay ban đầu,Tiền giải ngân,Cần Giải Ngân,Tiền gốc còn lại,Đã trả/khoản vay đã giải ngân,LongestOverdue,LoanTermMonths,LoanToIncomeRatio,HasLatePayment,HasBadDebt,LoanStatus
0,16104,12603108,Cầm cố Điện thoại,NaN,Hà Nội,10000000.0,10000000.0,0.0,10000000.0,1.00,4,1,1.30,0,0,Active
1,20871,12603108,Cầm cố Điện thoại,2016-07-28,Hà Nội,10000000.0,10000000.0,0.0,0.0,0.00,147,8,1.30,0,0,Completed
2,17049,1075003746,Unknown,2016-06-29,Hà Nội,5000000.0,5000000.0,0.0,5000000.0,1.00,3,6,0.19,0,0,Completed
3,17067,1089003832,Cầm cố Điện thoại,2016-06-29,Hà Nội,10000000.0,10000000.0,0.0,10000000.0,1.00,16,4,1.25,0,0,Completed
4,22390,1182005991,Cầm cố Điện thoại,2016-08-05,Hà Nội,10000000.0,10000000.0,0.0,0.0,0.00,8,4,0.83,0,0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,56967,331764079,Cầm cố Điện thoại,2018-12-24,Hồ Chí Minh,5000000.0,5000000.0,0.0,1814424.0,0.36,0,3,0.67,0,0,Active
2379,56835,60526843,Vay trực tuyến qua Sim,2018-12-22,Yên Bái,3000000.0,3000000.0,0.0,3000000.0,1.00,2,2,0.38,0,0,Completed
2380,57212,35091001441,Cầm cố xe máy,2018-12-27,Hà Nội,6000000.0,6000000.0,0.0,6000000.0,1.00,0,3,0.75,0,0,Completed
2381,57938,151505959,Cầm cố xe máy,2019-01-10,Hà Nội,7000000.0,6000000.0,1000000.0,6000000.0,1.00,0,3,0.58,0,0,Completed
2382,58148,30094001694,Cầm cố xe máy,2019-01-13,Hà Nội,10000000.0,10000000.0,0.0,10000000.0,1.00,-3,3,0.71,0,0,Active

In [32]:
fact_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   LoanID                         2383 non-null   int64
 1   CardNumber                     2383 non-null   int64
 2   ProductCreditName              2383 non-null   object
 3   application_date               2382 non-null   object
 4   CityName                       2383 non-null   object
 5   Số tiền đăng ký vay ban đầu    2383 non-null   float64
 6   Tiền giải ngân                 2383 non-null   float64
 7   Cần Giải Ngân                  2383 non-null   float64
 8   Tiền gốc còn lại               2383 non-null   float64
 9   Đã trả/khoản vay đã giải ngân  2383 non-null   float64
 10  LongestOverdue                 2383 non-null   int64
 11  LoanTermMonths                 2383 non-null   int64
 12  LoanToIncomeRatio              2383 non-null   float64
 13  HasLatePayment                 2383 non-null   int64
 14  HasBadDebt                     2383 non-null   int64
 15  LoanStatus                     2383 non-null   object
dtypes: float64(6), int64(6), object(4)
memory usage: 298.0+ KB